PPP Web/PPP Web/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PPP_Web.Models;
using PPP_Web.Models.AuxData;

namespace PPP_Web.Controllers
{
    public class CitiesController : Controller
    {
        private PPP_WebContext db = new PPP_WebContext();

        // GET: Cities
        public async Task<ActionResult> Index()
        {
            return View(await db.Cities.ToListAsync());
        }

        // GET: Cities/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.FindAsync(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: Cities/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.FindAsync(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        //// POST: Cities/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit([Bind(Include = "Id,Name")] City city)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(city).State = EntityState.Modified;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }
        //    return View(city);
        //}

        // GET: Cities/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.FindAsync(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            City city = await db.Cities.FindAsync(id);
            db.Cities.Remove(city);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PPP Web/PPP Web/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PPP_Web.Models;

namespace PPP_Web.Controllers
{
    public class MembersController : Controller
    {
        private PPP_WebContext db = new PPP_WebContext();

        // GET: Members
        public ActionResult Index()
        {
            var members = db.Members.Include(m => m.City);
            return View(members.ToList());
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name");
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Address,PostCode,CityId,BirthDate,Gender,Signature,TimeCreated,Email,PhoneNr,WantInfo,IceName,IceRole,IcePhone")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", member.CityId);
            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", member.CityId);
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude = "BirthDate, TimeCreated, Signature", Include = "Id,FirstName,LastName,Address,PostCode,CityId,Gender,Email,PhoneNr,WantInfo,IceName,IceRole,IcePhone")] Member updatedMember)
        {
            if (ModelState.IsValid)
            {
                var oldMember = db.Members.AsQueryable().FirstOrDefault(m => m.Id == updatedMember.Id);
                oldMember.FirstName = updatedMember.FirstName;
                oldMember.LastName = updatedMember.LastName;
                oldMember.Address = updatedMember.Address;
                oldMember.PostCode = updatedMember.PostCode;
                oldMember.CityId = updatedMember.CityId;
                oldMember.Gender = updatedMember.Gender;
                oldMember.Email = updatedMember.Email;
                oldMember.PhoneNr = updatedMember.PhoneNr;
                oldMember.WantInfo = updatedMember.WantInfo;
                oldMember.IceName = updatedMember.IceName;
                oldMember.IceRole = updatedMember.IceRole;
                oldMember.IcePhone = updatedMember.IcePhone;

                db.Entry(oldMember).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Stats", new { oldMember.FullName});
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", updatedMember.CityId);
            return View(updatedMember);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("Index", "Stats");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PPP Web/PPP Web/Controllers/StatsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PPP_Web.Models;
using PPP_Web.Repository;
using AutoMapper;
using System.Web.Http.Description;
using PPP_Web.ViewModels;
using PPP_Web.Models.AuxData;
using System.Drawing;
using System.IO;
using System.Reflection;

namespace PPP_Web.Controllers
{
    public class StatsController : Controller
    {
        private PPP_WebContext db = new PPP_WebContext();
        private readonly IGenericRepository<Guest> _guestRepository;
        private readonly IGenericRepository<MemberLog> _memberLogRepository;
        private readonly IGenericRepository<Member> _memberRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public StatsController(IMapper mapper, IUnitOfWork unitOfWork, IGenericRepository<MemberLog> memberLogRepository, IGenericRepository<Guest> guestRepository, IGenericRepository<Member> memberRepository)
        {
            this._guestRepository = guestRepository;
            this._memberLogRepository = memberLogRepository;
            this._memberRepository = memberRepository;
            this._unitOfWork = unitOfWork;
            this._mapper = mapper;
        }

        // GET: Stats
        public ActionResult Index() //How to make async?
        {
            var guests = _guestRepository.AsQueryable();
            var guestsVm = _mapper.Map<List<GuestViewModel>>(guests);
            var memberLogs = _memberLogRepository.AsQueryable();
            var memberlogsVm = _mapper.Map<List<MemberLogViewModel>>(memberLogs);
            var members = _memberRepository.AsQueryable();
            var membersVm = _mapper.Map<List<Member>>(members);

            var data = new DataViewModel
            {
                Guests = guestsVm,
                MemberLogs = memberlogsVm,
                Members = membersVm
            };

            return View(data);
        }

        // GET: Stats/Details/5
        public async Task<ActionResult> Details(string fullname)
        {
            if (fullname == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var member = _memberRepository.AsQueryable().FirstOrDefault(x => string.Equals(x.FirstName + " " + x.LastName, fullname));
            if (member == null)
            {
                return HttpNotFound();
            }
            if (member.Signature != null)
            {
                //var assembly = System.Reflection.Assembly.GetExecutingAssembly();
                //using (var stream = assembly.GetManifestResourceStream("PPP_Web.Images.sample.bmp"))
                //{
                //    byte[] buffer = new byte[stream.Length];
                //    stream.Read(buffer, 0, buffer.Length);
                //    ViewBag.ImageData = buffer;
                //}
                //MemoryStream ms = new MemoryStream();
                //Bitmap bmp = new Bitmap(System.Reflection.Assembly.GetEntryAssembly().GetManifestResourceStream("PPP_Web.Images.sample.bmp"));
                //bmp.Save(ms, System.Drawing.Imaging.ImageFormat.Gif);
                ////ViewBag.ImageData = ms.ToArray();
                ViewBag.ImageData = member.Signature;
            }
            return View(member);
        }

        // GET: Stats/Create
        public ActionResult Create()
        {
            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name");
            return View();
        }

        // POST: Stats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Gender,TimeCreated,SchoolId")] Guest guest)
        {
            if (ModelState.IsValid)
            {
                db.Guests.Add(guest);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name", guest.SchoolId);
            return View(guest);
        }

        // GET: Stats/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = await _memberRepository.GetByKeyAsync(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", member.CityId);
            return View(member);
        }

        // POST: Stats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,FirstName,LastName,Address,PostCode,CityId,BirthDate,Gender,Signature,TimeCreated,Email,PhoneNr,WantInfo,IceName,IceRole,IcePhone")] Member member)
        {
            if (ModelState.IsValid)
            {
                School newSchool = new School { Name = member.City.Name };
                db.Entry(member).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", member.CityId);
            return View(member);
        }

        // GET: Stats/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guest guest = await db.Guests.FindAsync(id);
            if (guest == null)
            {
                return HttpNotFound();
            }
            return View(guest);
        }

        // POST: Stats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Guest guest = await db.Guests.FindAsync(id);
            db.Guests.Remove(guest);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PPP Web/PPP Web/Views/Stats/Create.cshtml
@model PPP_Web.Models.Guest

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Guest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SchoolId, "SchoolId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SchoolId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SchoolId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PPP Web/PPP Web/Views/Stats/Delete.cshtml
@model PPP_Web.Models.Guest

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Guest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.School.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.School.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PPP Web/PPP Web/Views/Stats/Details.cshtml
@model PPP_Web.Models.Member

@{
    ViewBag.Title = "Detaljer";
}

<h2>Detaljer</h2>

<div>
    <h4>Medlem</h4>
    <hr />
    <table class="table">
        <tr>
            <td>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.FullName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FullName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Gender)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Gender)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.BirthDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BirthDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.WantInfo)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.WantInfo)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PostCode)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PostCode)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.City.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.City.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNr)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNr)
                    </dd>

                </dl>
            </td>
            <td>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.IceName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IceName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IceRole)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IceRole)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IcePhone)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IcePhone)
                    </dd>
                    @if (ViewBag.ImageData != null)
                    {
                        <dt>
                            @Html.DisplayNameFor(model => model.Signature)
                        </dt>

                        <dd>
                            @*<img src="@ViewBag.ImageData" />*@
                            <img src="data:image/png;base64,@ViewBag.ImageData" width="175" height="100" />
                        </dd>
                    }
                </dl>
            </td>
        </tr>
    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", "Members", new { id = Model.Id }, null) |
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Delete", "Delete", "Members", new { id = Model.Id}, null)
</p>

PPP Web/PPP Web/Views/Stats/Edit.cshtml
@model PPP_Web.Models.Member

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "api/Members"))
{
    @Html.HttpMethodOverride(HttpVerbs.Put)
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                @Html.ActionLink("Add new City", "Create", "Cities")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WantInfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.WantInfo)
                    @Html.ValidationMessageFor(model => model.WantInfo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IceRole, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IceRole, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IceRole, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IcePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IcePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IcePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PPP Web/PPP Web/Views/Stats/Index.cshtml
@model PPP_Web.ViewModels.DataViewModel

@{
    ViewBag.Title = "Index";
    var dates = PPP_Web.Views.Stats.StatsUtils.getDates(Model);

    var MHighSchool = PPP_Web.Views.Stats.StatsUtils.getGuests(
        dates, true, PPP_Web.Views.Stats.StatsUtils.School.Högstadiet, Model);
    var FHighSchool = PPP_Web.Views.Stats.StatsUtils.getGuests(
        dates, false, PPP_Web.Views.Stats.StatsUtils.School.Högstadiet, Model);
    var MGymnasium = PPP_Web.Views.Stats.StatsUtils.getGuests(
        dates, true, PPP_Web.Views.Stats.StatsUtils.School.Gymnasium, Model);
    var FGymnasium = PPP_Web.Views.Stats.StatsUtils.getGuests(
        dates, false, PPP_Web.Views.Stats.StatsUtils.School.Gymnasium, Model);

    string[] names;
    var memberLogDates = PPP_Web.Views.Stats.StatsUtils.getMemberLogDates(dates, Model, out names);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <h2>Index</h2>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Datum:
                </th>
                @foreach (var time in dates)
                {
                    <th>
                        <p style="width: 10px;">@time.Date.ToString("yy MM dd")</p>
                    </th>
                }
            </tr>
        </thead>

        <tr>
            <td>
                Kille Högstadiet
            </td>
            @foreach (var count in MHighSchool)
            {
                <td>
                    @count
                </td>
            }
        </tr>
        <tr>
            <td>
                Tjej Högstadiet
            </td>
            @foreach (var count in FHighSchool)
            {
                <td>
                    @count
                </td>
            }
        </tr>
        <tr>
            <td>
                Kille Gymnasiet
            </td>
            @foreach (var count in MGymnasium)
            {
                <td>
                    @count
                </td>
            }
        </tr>
        <tr>
            <td>
                Tjej Gymnasiet
            </td>
            @foreach (var count in FGymnasium)
            {
                <td>
                    @count
                </td>
            }
        </tr>

        @foreach (var name in names)
        {
            <tr>
                <td>
                    @Html.ActionLink(name, "Details", "Stats", new { fullname = name }, null)
                </td>
                @foreach (var presence in memberLogDates[name])
                {
                    <td>
                        @presence
                    </td>
                }
            </tr>
        }
    </table>

    @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@

</body>
</html>